In [2]:
import numpy as np

X = np.array([[0,1],[1,0],[3,2],[3,3]])
Y = np.array([[0],[0],[1],[1]])
print(X)
print(Y)

[[0 1]
 [1 0]
 [3 2]
 [3 3]]
[[0]
 [0]
 [1]
 [1]]


In [7]:
def gd(x, y, step_size, iterations):
    print("x", x.shape)
    print("y", y.shape)
    u = step_size

    # Initializing weights
    w = np.random.randn(x.shape[1], 1)
    print('w', w.shape)

    # Gradient Descent
    for i in range(iterations):

        # Calculating gradient
        grad = 1/4 * x.T @ ((1 / (1 + np.exp(-x@w))) - y)

        # Updating weights based on gradient
        w = w - u * (grad)

    print("\nGradient:\n\t ", grad)
    print("\nOptimal Weights:\n\t ", w)

    return w

In [10]:
gd(X,Y, 0.1, 1000)

x (4, 2)
y (4, 1)
w (2, 1)


Loss:
	  [[ 4.72176420e-05]
 [-5.58999058e-05]]

Gradient of Loss:
	  [[ 4.72176420e-05]
 [-5.58999058e-05]]

Optimal Weights:
	  [[0.60017752]
 [0.126677  ]]


array([[0.60017752],
       [0.126677  ]])