In [23]:
import numpy as np
import sklearn.preprocessing as pre
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures


In [60]:
A = np.array([4, 7, 9, 11, 15])
B = np.array([18, 22, 25, 30, 35, 40])
C = np.array([12, 14, 16, 18, 20])
D = np.array([28, 32, 36, 40, 44, 48])

print("Empirical Variance of A: ", np.var(A, ddof=1))
print("Empirical Variance of B: ", np.var(B, ddof=1))
print("Population Variance of C: ", np.var(C, ddof=0))
print("Population Variance of D: ", np.var(D, ddof=0))

Empirical Variance of A:  17.2
Empirical Variance of B:  68.26666666666668
Population Variance of C:  8.0
Population Variance of D:  46.666666666666664


Population variance is calculated with 1/N, Empirical variance is calculated with 1/(N-1). Population variance is used when there is data for the entire population. Empirical is used when only a subset is available. If you were taking the variance of the weight of everyone in the world, there is no reason to collect and process 8 billion datapoints when 1 million would yield very similar results, hence empirical should be used in that situation. If you are measuring the variance of GPA of people at Northeastern, population variance is more appropriate because the data is available and small enough to process.

In [15]:
X = np.array([[1,-2,0,1],[-2,-1,1,2],[1,2,-1,1]])
Y = np.array([[2],[3],[-1]])

def gd(x, y, step_size, iterations):
    
    u = step_size
    L = 2
    w = np.array([[-1],[0],[1],[1]])
    
    print("x", x.shape)
    print("y", y.shape)
    print('w', w.shape)
    
    # Gradient Descent
    for i in range(iterations):

        # Calculating gradient
        grad = 2*x.T@(x@w - y) + 2*L*w
        
        # Updating weights based on gradient
        w = w - u * (grad)
        print(i, "\n", w)
    # Printing Results
    print("\nGradient:\n\t ", grad)
    print("\nOptimal Weights:\n\t ", w)

    return w

gd(X, Y, 0.5, 2)

x (3, 4)
y (3, 1)
w (4, 1)
0 
 [[ 7.]
 [-2.]
 [-3.]
 [-3.]]
1 
 [[-65.]
 [-18.]
 [ 31.]
 [ 41.]]

Gradient:
	  [[144.]
 [ 32.]
 [-68.]
 [-88.]]

Optimal Weights:
	  [[-65.]
 [-18.]
 [ 31.]
 [ 41.]]


array([[-65.],
       [-18.],
       [ 31.],
       [ 41.]])

In [17]:
y = np.array([[7],[-24],[4]])
z= np.array([[2,-4,2],[-4,-2,4],[0,2,-2],[2,4,2]])
print(z@y)


[[118]
 [ 36]
 [-56]
 [-74]]


In [36]:
X = np.genfromtxt('stock_prediction_data.csv', delimiter=',')
print(X.shape)

Y = np.genfromtxt('stock_price.csv', delimiter=',')
Y = Y.reshape([-1,1])
print(Y.shape)

def preprocess(x,y):
    # 1: Scale and Center the data
    scaler = pre.StandardScaler().fit(x)
    x = scaler.transform(x)
    print("x-std: ", x.std())
    print("x-mean: ", x.mean())
    # 2: Split into train (80%) and remaining (20%)
    x_train, x_temp, y_train, y_temp = train_test_split(x, y, test_size=0.2, random_state=22)

    # 3: Split remaining into val (10%) and test (10%)
    x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, test_size=0.5, random_state=22)
    y_test = y_test.reshape(-1, 1)
    y_val = y_val.reshape(-1, 1)
    y_train = y_train.reshape(-1, 1)

    print("\nX-train shape: ", x_train.shape)
    print("Y-train shape: ", y_train.shape)

    print("\nX-val shape: ", x_val.shape)
    print("Y-val shape: ", y_val.shape)

    print("\nX-test shape: ", x_test.shape)
    print("Y-test shape: ", y_test.shape)
    return x_train, y_train, x_val, y_val, x_test, y_test

x_train, y_train, x_val, y_val, x_test, y_test = preprocess(X, Y)

(300, 10)
(300, 1)
x-std:  1.0
x-mean:  8.289665250534503e-17

X-train shape:  (240, 10)
Y-train shape:  (240, 1)

X-val shape:  (30, 10)
Y-val shape:  (30, 1)

X-test shape:  (30, 10)
Y-test shape:  (30, 1)


In [49]:
def poly_gd(x, y, step_size, iterations, degree, lambda_val):
    print("x", x.shape)
    print("y", y.shape)
    u = step_size

    poly = PolynomialFeatures(degree=degree, include_bias=False)
    X = poly.fit_transform(x)

    # Initializing weights
    w = np.random.randn(X.shape[1], 1)
    print('w', w.shape)

    # Gradient Descent
    for i in range(iterations):

        # Calculating gradient
        grad = 2 * X.T @ (X @ w - y) + lambda_val * np.sign(w)

        # Updating weights based on gradient
        w = w - u * (grad)

    # Printing Results
    print("\n\nGrad:\n ", grad)
    print("\nOptimal Weights:\n ", w)

    return w


w = poly_gd(x_train, y_train, 0.00001, 100000, 2, 0.01)

x (240, 10)
y (240, 1)
w (65, 1)


Grad:
  [[ 2.55871713e-14]
 [-2.21371480e-11]
 [-1.53887320e-14]
 [ 4.38121761e-14]
 [-5.52000286e-12]
 [ 2.19568790e-11]
 [ 4.41122850e-11]
 [-2.20425136e-11]
 [-4.98786255e-12]
 [-1.09671404e-11]
 [ 6.27654179e-13]
 [-1.28690461e-13]
 [-5.10667897e-14]
 [-5.92286636e-14]
 [-2.13648543e-14]
 [ 6.03562339e-14]
 [ 1.22108920e-13]
 [-1.85719495e-14]
 [-2.58126853e-14]
 [-7.62081370e-14]
 [-6.01151073e-13]
 [ 1.41345269e-14]
 [ 1.35516598e-14]
 [ 1.98435018e-14]
 [-6.38898656e-14]
 [-3.75741105e-15]
 [ 3.25937194e-14]
 [-9.94863913e-14]
 [-1.84557231e-14]
 [ 5.84835999e-13]
 [-5.62397351e-15]
 [ 1.33448808e-13]
 [ 5.50948176e-14]
 [-1.80654103e-14]
 [ 3.40505402e-13]
 [ 3.85767807e-14]
 [ 1.41891707e-13]
 [-6.54807805e-13]
 [ 2.91549770e-13]
 [ 6.15237028e-14]
 [-4.10609047e-14]
 [-1.99996270e-14]
 [ 8.76035355e-15]
 [ 9.80743264e-14]
 [ 6.48365042e-13]
 [-2.71255240e-13]
 [-3.24813093e-13]
 [-9.38485401e-16]
 [ 6.39575198e-14]
 [ 3.21895288e-14]
 [ 5.41

In [43]:
from sklearn.linear_model import Lasso

poly = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(x_train)

model = Lasso(alpha=0.01, max_iter=10000)  # alpha ~ lambda
model.fit(X_poly, y_train)

print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [ 0.00000000e+00  3.99277961e+00  0.00000000e+00 -3.98044534e-03
  9.66232434e-01  2.98939878e+00  3.98212720e+00  2.96959922e+00
  9.72099428e-01  1.02061757e+00 -0.00000000e+00  0.00000000e+00
  2.28370096e-03  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
  6.50799768e-03 -2.17836219e-03  0.00000000e+00 -0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00  0.00000000e+00  1.10659907e-02  6.05462362e-03
 -3.18225231e-03  0.00000000e+00 -2.00912343e-02  0.00000000e+00
 -2.22912054e-03 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -1.11559439e-02  2.60187029e-02 -2.53949581e-02 -0.00000000e+00
  2.78716408e-03  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00 -9.93555737e-04
 -1.82217959e-03  0.00000000e+00  0.00000000e+00  1.28387844e-03
  0.0000000

In [54]:
best_lambda = None
best_val_score = float('Inf')
for val in [0.001, 0.1, 1, 2, 3, 4, 5, 10]:
    w = poly_gd(x_train, y_train, 0.000001, 10000, 2, val)
    poly = PolynomialFeatures(degree=2, include_bias=False)
    X_val_poly = poly.fit_transform(x_val)
    predictions = X_val_poly @ w
    val_score = np.mean((predictions - y_val) ** 2)
    if val_score < best_val_score:
        best_val_score = val_score
        best_lambda = val
print("BEST LAMBDA: ", best_lambda)
print("BEST VAL SCORE: ", best_val_score)

x (240, 10)
y (240, 1)
w (65, 1)


Grad:
  [[-33.00583867]
 [-37.87829279]
 [-35.02607896]
 [ -7.53130631]
 [-12.21044355]
 [-35.92277961]
 [-20.42171961]
 [-31.07336232]
 [ -3.29165293]
 [  2.75221532]
 [ 11.03420799]
 [  0.27178337]
 [  8.35522002]
 [ 21.79422002]
 [-18.91063834]
 [-47.59101868]
 [  6.87168436]
 [  8.26210842]
 [ -1.87435596]
 [ 26.05322797]
 [-25.51754772]
 [-12.64501386]
 [-20.88730636]
 [-24.9547988 ]
 [-26.93434235]
 [ 11.18680068]
 [-28.87419655]
 [-10.78104379]
 [ 18.42139214]
 [ 39.95326943]
 [ 12.12163985]
 [ 13.14533299]
 [  1.45224953]
 [-33.44273635]
 [-36.91995424]
 [ -3.89524846]
 [-26.38316414]
 [-15.57003516]
 [-19.65405892]
 [  3.31903813]
 [  9.03323271]
 [ -5.51626793]
 [-34.01338357]
 [ 17.51971361]
 [  6.73947428]
 [ 36.92419768]
 [ 12.03970818]
 [ 19.0392471 ]
 [  6.90990887]
 [  9.84994578]
 [ 16.26434957]
 [ -4.56256285]
 [-12.70283117]
 [ -9.33350333]
 [ 12.24658935]
 [-23.88756298]
 [-12.66759267]
 [-13.12909971]
 [ 11.16509263]
 [-48.1075393

In [47]:
def poly_ridge_gd(x, y, step_size, iterations, degree, lambda_val):
    print("x", x.shape)
    print("y", y.shape)
    u = step_size

    poly = PolynomialFeatures(degree=degree, include_bias=False)
    X = poly.fit_transform(x)

    # Initializing weights
    w = np.random.randn(X.shape[1], 1)
    print('w', w.shape)

    # Gradient Descent
    for i in range(iterations):
        # Calculating gradient
        grad = 2 * X.T @ (X @ w - y) + lambda_val * 2 * w

        # Updating weights based on gradient
        w = w - u * (grad)

    # Printing Results
    print("\n\nGrad:\n ", grad)
    print("\nOptimal Weights:\n ", w)

    return w

w = poly_gd(x_train, y_train, 0.00001, 100000, 2, 0.01)

x (240, 10)
y (240, 1)
w (65, 1)


Grad:
  [[-2.54150788e-03]
 [-8.83605913e-04]
 [ 1.33074914e-03]
 [-1.23969979e-03]
 [ 6.42659077e-04]
 [-6.61162109e-04]
 [ 1.88681996e-04]
 [-9.91738905e-06]
 [ 7.71681103e-04]
 [ 6.24516641e-04]
 [-9.27697845e-04]
 [ 6.37205204e-04]
 [ 3.22956450e-04]
 [ 1.12629962e-03]
 [ 1.92453258e-03]
 [-2.66374352e-03]
 [-1.31939626e-03]
 [ 1.03288747e-03]
 [ 7.29550502e-04]
 [ 2.03059540e-03]
 [-2.04312500e-03]
 [ 4.62495291e-04]
 [-3.06261822e-04]
 [-1.13203977e-03]
 [-6.37010441e-04]
 [ 3.32908265e-03]
 [-7.83118170e-04]
 [ 2.34392794e-04]
 [-5.17010014e-04]
 [-9.12869665e-04]
 [-2.21662653e-03]
 [-2.46070194e-03]
 [ 4.80211315e-04]
 [-1.46125159e-03]
 [-3.60534312e-04]
 [-3.79076144e-03]
 [-3.84128881e-03]
 [ 1.27042545e-03]
 [-2.24371497e-03]
 [ 2.64016961e-04]
 [ 1.47339164e-03]
 [ 3.21282002e-04]
 [-2.43491171e-04]
 [-6.48436744e-04]
 [-3.18628956e-03]
 [ 3.52595836e-03]
 [ 2.11695601e-03]
 [-1.18776465e-03]
 [-2.41066671e-03]
 [-1.96336670e-03]
 [ 3.61

In [48]:
from sklearn.linear_model import Ridge

poly = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(x_train)

model = Ridge(alpha=0.01, max_iter=10000)  # alpha ~ lambda
model.fit(X_poly, y_train)

print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [[-1.24554443e-03  4.00417474e+00  8.81553935e-03 -1.29754478e-02
   9.76231079e-01  3.00559749e+00  3.99429979e+00  2.98327197e+00
   9.82157145e-01  1.03386260e+00 -8.03259655e-03  4.15802917e-03
   1.96219854e-02  1.68370123e-02 -4.11642145e-04 -5.42008387e-03
  -5.19431037e-03 -6.89729990e-03  1.09585502e-02  9.47070682e-03
   2.41324591e-02 -1.35785758e-02  1.02263148e-02 -1.63788352e-03
  -4.52980908e-04 -1.82949111e-03  7.83667088e-03  9.11461532e-03
  -9.31373675e-03  1.08961335e-02 -5.51974624e-03 -9.47814974e-03
   3.66903902e-03  1.42260301e-02  2.34182758e-02  1.52679084e-02
  -3.10346552e-02  1.17885647e-02 -2.85770330e-02  2.59786546e-03
  -9.01290047e-03 -4.33611543e-03  5.00111125e-03 -9.52049637e-03
  -2.12280518e-02  3.97544708e-02 -3.76853039e-02 -1.50081660e-03
   6.30938619e-03 -1.82707233e-03  1.73092286e-03 -1.28485564e-02
   3.37460575e-03  1.16453875e-02  9.04720759e-03 -1.70811842e-02
  -2.56633300e-03  1.05844608e-03  1.70370313e-02  1.81624080e

In [53]:
best_lambda = None
best_val_score = float('Inf')
for val in [0.001, 0.1, 1, 2, 3, 4, 5, 10]:
    w = poly_ridge_gd(x_train, y_train, 0.00001, 10000, 2, val)
    poly = PolynomialFeatures(degree=2, include_bias=False)
    X_val_poly = poly.fit_transform(x_val)
    predictions = X_val_poly @ w
    val_score = np.mean((predictions - y_val) ** 2)
    if val_score < best_val_score:
        best_val_score = val_score
        best_lambda = val
print("BEST LAMBDA: ", best_lambda)
print("BEST VAL SCORE: ", best_val_score)

x (240, 10)
y (240, 1)
w (65, 1)


Grad:
  [[ 1.81340547e-04]
 [-4.45829073e-04]
 [-4.84572269e-05]
 [-2.08343938e-04]
 [-1.88425057e-04]
 [-2.61029036e-04]
 [ 3.70461277e-04]
 [ 2.61554572e-05]
 [ 4.99322639e-05]
 [ 8.60657605e-05]
 [ 9.99608015e-06]
 [-1.64198696e-04]
 [ 1.01035712e-04]
 [-3.28768978e-04]
 [ 8.03776698e-05]
 [-3.14596948e-04]
 [ 1.19875719e-04]
 [-1.25728814e-04]
 [-1.52477120e-04]
 [-9.92336426e-06]
 [-6.55680581e-04]
 [ 4.92326010e-04]
 [ 2.83144203e-04]
 [ 5.05958347e-04]
 [-3.26550646e-04]
 [ 2.74059712e-04]
 [-1.95484495e-04]
 [ 7.06175647e-05]
 [ 2.36572102e-04]
 [-1.95319992e-04]
 [-2.36803230e-04]
 [-3.29453190e-05]
 [ 1.20097339e-04]
 [-6.93581195e-04]
 [ 2.22450990e-04]
 [-4.70953586e-04]
 [ 3.35290636e-04]
 [-4.62397168e-05]
 [-4.47837476e-04]
 [ 4.60590563e-04]
 [-1.63671422e-04]
 [ 6.27628918e-06]
 [-8.81245980e-05]
 [-5.58326116e-05]
 [-4.26120927e-04]
 [ 6.30651478e-04]
 [-3.13852609e-05]
 [-2.85316361e-04]
 [ 6.41378593e-05]
 [ 6.61759982e-05]
 [ 4.29

In [55]:
def poly_elastic_net_gd(x, y, step_size, iterations, degree, lambda_val):
    print("x", x.shape)
    print("y", y.shape)
    u = step_size

    poly = PolynomialFeatures(degree=degree, include_bias=False)
    X = poly.fit_transform(x)

    # Initializing weights
    w = np.random.randn(X.shape[1], 1)
    print('w', w.shape)

    # Gradient Descent
    for i in range(iterations):
        # Calculating gradient
        grad = 2 * X.T @ (X @ w - y) + lambda_val * 2 * w + lambda_val * np.sign(w)

        # Updating weights based on gradient
        w = w - u * (grad)

    # Printing Results
    print("\n\nGrad:\n ", grad)
    print("\nOptimal Weights:\n ", w)

    return w

w = poly_gd(x_train, y_train, 0.00001, 100000, 2, 0.01)

x (240, 10)
y (240, 1)
w (65, 1)


Grad:
  [[-7.67094721e-14]
 [ 2.20564227e-11]
 [ 1.84678661e-14]
 [-3.11400211e-14]
 [ 5.47919175e-12]
 [-2.20186057e-11]
 [-4.42068882e-11]
 [ 2.21224671e-11]
 [ 5.48077382e-12]
 [ 1.09702681e-11]
 [-6.45952042e-13]
 [ 1.52622706e-13]
 [ 5.03330017e-14]
 [ 6.63427646e-14]
 [-5.43488865e-15]
 [-7.98805466e-14]
 [-1.60114977e-13]
 [ 2.62879996e-14]
 [-1.76247905e-15]
 [ 5.45778700e-14]
 [ 5.95069133e-13]
 [ 1.39246253e-14]
 [-1.10918219e-14]
 [-1.99458505e-14]
 [ 8.10879142e-14]
 [-1.13450915e-15]
 [-6.49168219e-14]
 [ 9.28944421e-14]
 [ 9.88618909e-15]
 [-5.99848296e-13]
 [ 4.28129754e-15]
 [-1.43433876e-13]
 [-4.48009685e-14]
 [ 9.91966925e-14]
 [-2.95282895e-13]
 [-5.13027121e-14]
 [-1.61549593e-13]
 [ 6.03860711e-13]
 [-3.12807072e-13]
 [-3.96505745e-14]
 [ 4.02473194e-14]
 [ 1.47416801e-14]
 [ 8.31626434e-15]
 [-1.01554182e-13]
 [-6.82013473e-13]
 [ 3.18880339e-13]
 [ 3.28176722e-13]
 [-1.85372551e-14]
 [-1.55729596e-13]
 [ 2.73895490e-14]
 [-6.28

In [56]:
from sklearn.linear_model import ElasticNet

poly = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(x_train)

model = ElasticNet(alpha=0.01, max_iter=10000)  # alpha ~ lambda
model.fit(X_poly, y_train)

print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [ 1.63328878e-03  3.97685526e+00  0.00000000e+00 -8.50713528e-03
  9.66325193e-01  2.98003176e+00  3.96796432e+00  2.96015384e+00
  9.70119258e-01  1.02346794e+00 -0.00000000e+00  0.00000000e+00
  6.44808240e-03  6.48401665e-03 -0.00000000e+00 -3.67381243e-03
  0.00000000e+00 -2.42217702e-03  2.39715990e-03  6.88568399e-04
  1.20571087e-02 -5.59489217e-03  1.81811440e-03 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  1.03336216e-03
 -0.00000000e+00  6.61449941e-03 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  4.43712004e-03  1.45985652e-02  9.10374478e-03
 -1.38034678e-02  1.54124977e-03 -2.22339612e-02  0.00000000e+00
 -5.55068952e-03 -0.00000000e+00  0.00000000e+00 -3.71995450e-03
 -1.65288180e-02  3.22534019e-02 -2.88880405e-02 -0.00000000e+00
  5.26975296e-03  0.00000000e+00  3.55507418e-04 -5.54382498e-03
 -0.00000000e+00  2.68128281e-03  0.00000000e+00 -1.08028350e-02
 -4.57476484e-03  0.00000000e+00  6.33814914e-03  1.06156506e-02
  1.8552564

In [57]:
best_lambda = None
best_val_score = float('Inf')
for val in [0.001, 0.1, 1, 2, 3, 4, 5, 10]:
    w = poly_elastic_net_gd(x_train, y_train, 0.00001, 10000, 2, val)
    poly = PolynomialFeatures(degree=2, include_bias=False)
    X_val_poly = poly.fit_transform(x_val)
    predictions = X_val_poly @ w
    val_score = np.mean((predictions - y_val) ** 2)
    if val_score < best_val_score:
        best_val_score = val_score
        best_lambda = val
print("BEST LAMBDA: ", best_lambda)
print("BEST VAL SCORE: ", best_val_score)

x (240, 10)
y (240, 1)
w (65, 1)


Grad:
  [[ 5.98117803e-04]
 [-8.71212307e-04]
 [-4.90308608e-04]
 [-2.23266550e-04]
 [-5.87386972e-04]
 [-3.34981568e-04]
 [ 9.20666811e-04]
 [ 1.40990772e-04]
 [ 4.64696649e-04]
 [ 4.60877037e-04]
 [ 1.48746821e-05]
 [-1.11039865e-03]
 [-1.23544724e-04]
 [-4.93092504e-04]
 [-9.90186842e-04]
 [-2.64568347e-04]
 [ 9.17187037e-04]
 [-1.09457716e-03]
 [-2.38818226e-04]
 [-2.51134164e-04]
 [-1.23717503e-03]
 [ 7.42769910e-04]
 [ 1.73491572e-03]
 [ 2.00430686e-03]
 [-9.21112042e-04]
 [ 4.39988701e-06]
 [ 3.44686936e-04]
 [ 2.48763389e-04]
 [-7.06089289e-04]
 [-6.86606717e-04]
 [ 5.64833884e-04]
 [ 2.11507020e-04]
 [ 7.79946985e-04]
 [-9.77681277e-04]
 [ 5.55890781e-04]
 [-7.33489799e-04]
 [ 4.34461040e-04]
 [ 3.41786913e-04]
 [-3.19151012e-04]
 [ 1.31998515e-03]
 [-3.38180322e-04]
 [ 1.01104064e-05]
 [-3.75730203e-06]
 [ 4.64803950e-06]
 [-8.29975704e-05]
 [ 1.65360087e-03]
 [-6.94923617e-04]
 [ 3.12725518e-04]
 [-1.69511739e-04]
 [-2.30898866e-04]
 [ 4.75

Elastic net pushes irrelevant features to zero like L1, but also yields the good results of L2 constraint