In [21]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [22]:
df = pd.read_csv('golf.csv')
print(df)

# Create a copy to avoid changing the original
df_encoded = df.copy()

# Initialize LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to each column
for column in df_encoded.columns:
    df_encoded[column] = le.fit_transform(df_encoded[column])
    
# Convert to NumPy array
data_array = df_encoded.to_numpy()

# Print result
print(data_array)


     Outlook  Temp     Hum  Windy Golf
0      Rainy   Hot    High  False   No
1      Rainy   Hot    High   True   No
2   Overcast   Hot    High  False  Yes
3      Sunny  Mild    High  False  Yes
4      Sunny  Cool  Normal  False  Yes
5      Sunny  Cool  Normal   True   No
6   Overcast  Cool  Normal   True  Yes
7      Rainy  Mild    High  False   No
8      Rainy  Cool  Normal  False  Yes
9      Sunny  Mild  Normal  False  Yes
10     Rainy  Mild  Normal   True  Yes
11  Overcast  Mild    High   True  Yes
12  Overcast   Hot  Normal  False  Yes
13     Sunny  Mild    High   True   No
[[1 1 0 0 0]
 [1 1 0 1 0]
 [0 1 0 0 1]
 [2 2 0 0 1]
 [2 0 1 0 1]
 [2 0 1 1 0]
 [0 0 1 1 1]
 [1 2 0 0 0]
 [1 0 1 0 1]
 [2 2 1 0 1]
 [1 2 1 1 1]
 [0 2 0 1 1]
 [0 1 1 0 1]
 [2 2 0 1 0]]


In [25]:
def H(y):
    entropy = 0
    for i in range(len(np.unique(y))):
        py_i = np.where(y==i, 1, 0)
        py = np.sum(py_i)/len(y)
        py = py*np.log(py)
        entropy += py
    entropy = -entropy
    return entropy
def cross_entropy(y,x):
    cross_entropy = 0
    
print(H(data_array[:,0]))
print(H(data_array[:,1]))
print(H(data_array[:,2]))
print(H(data_array[:,3]))
print(H(data_array[:,4]))

(14, 5)
1.0933747175566468
1.0789922078775833
0.6931471805599453
0.6829081047004717
0.6517565611726531
